[package]
name = "lox_interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
miette = { version = "7", features = ["fancy"] }
clap = { version = "4.5.41", features = ["derive"] }
thiserror = "2.0.12"
